openapi: 3.0.2
info:
  version: "1.0.0"
  title: "FVNet"
  description: >
    API endpoints exposed for the Merchant Partners.

    # Introduction

    Using these APIs the merchant partners will be able to interact with users to fund their user account or request payments from them. Once the merchant partner is on-boarded at FV bank, they will be issued with an access-client-token and a merchant partner id. All the blow apis are required to be called with the access-client-token in the header.

servers:
- url: 'https://dev.api.fvbank.us'

tags:
  - name: Client
  - name: Account
  - name: Transactions

paths:
  /fvnet/checkAccountStatus/{drn}:
    get:
      tags:
      - "Account"
      summary: "Get the status of the account, ie Active and the balance"
      operationId: checkAccountStatus
      parameters:
      - name: drn
        in: path
        description: "The Deposit Reference Number of the account to check"
        required: true
        schema:
          type: string
      security:
      - accessClient: []
      responses:
        "200":
          description: "Return the balances of the account"
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/accountStatus"
        "500":
          description: "Internal Server Error"
  /fvnet/payment/push:
    post:
      tags:
      - "Transactions"
      summary: "Performs a payment from the given merchant partner to any user within the system"
      description: "Performs a direct payment from the merchant partner to to the user specified in the body. The destination user is identified by subject parameter. If the subject is system, it will be a payment to a system account. The payment id is returned on the response, and a link to the transaction details is returned on the Location header."
      operationId: "pushFunds"
      requestBody:
        description: "Request Body"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/paymentRequest"
      security:
      - accessClient: []
      responses:
        "500":
          description: "Internal server error"
        "200":
          description: "Successful"
          content: 
            text/plain: 
              schema:
                type: string
                example: "Success"
  /fvnet/payment/request:
    post:
      tags:
      - "Transactions"
      summary: "merchant partner requests a payment from user identified by the DRN"
      description: "Performs either a direct, scheduled or recurring payment from the owner indicated on the path to the owner specified on the body. The destination user should be informed in the subject parameter. If the subject is system, it will be a payment to a system account. The payment id is returned on the response, and a link to the transaction details is returned on the Location header."
      operationId: "requestFunds"
      requestBody:
        description: "Request Body"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/paymentRequest"
      security:
      - accessClient: []
      responses:
        "500":
          description: "Internal server error"
        "200":
          description: "Successful"
          content: 
            text/plain: 
              schema:
                type: string
                example: "Success"
  /fvnet/upload/invoice:
    post:
      tags:
      - "Transactions"
      summary: "Uploads a new invoice."
      description: "Uploads a new invoice. The returned id can later be used as value of a 'Payment_Invoice' custom field in the fvnet calls"
      operationId: "uploadInvoice"
      requestBody:
        description: "Request Parameters"
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadInvoice"
      security:
      - accessClient: []
      responses:
        "201":
          description: "Returns an id to be used later in the pushfunds or paymentrequests calls on the 'Payment_Invoice' custom field"
        "500":
          description: "Internal server error"
  /fvnet/access-client/activate:
    post:
      tags:
      - Client
      summary: "Get access client token using the client activation code."
      description: "Get access client token using the client activation code. This is required to be run once per client setup. The activation code will be provided during the setup of the MP setup."
      operationId: activateClient
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      security:
      - basicAuth: []
      responses:
        200:
          description: OK



              

components:
  schemas:
    uploadInvoice:
      type: object
      required:
        - file
        - customField
        - customFieldKind
      properties:
        file:
          type: string
          format: binary
          description: "The Invoice. Accepted formats: PDF, Word, Images, Excel"
        customField:
          type: string
          default: "Payment_Invoice"
          description: "Set to 'Payment_Invoice' always"
        customFieldKind:
          type: string
          default: "transaction"
          description: "Set to 'transaction' always"
    accountStatus:
      type: object
      properties:
        balance:
          type: string
          example: "100.91"
        status:
          type: string
          example: "ACTIVE"
        availableBalance:
          type: string
          example: "100.91"
        reservedAmount:
          type: string
          example: "0.00"
    paymentRequest:
      type: object
      required:
      - amount
      - expirationDate
      properties:
        amount:
          type: string
        customValues:
          type: object
          required:
          - Beneficiary_Payment_Purpose
          properties:
            Beneficiary_Payment_Purpose:
              type: string
              description: "Select an option from the purpose of payment."
              enum:
              - Asset Purchase
              - Contract Payment
              - Education Payment
              - Investment Purchase
              - Invoice Payment
              - Loan Payments
              - Materials Purchase
              - Mortgage Payments
              - Payroll
              - Personal/Family Payment
              - Professional Service Payments
              - Rent/Utility Payments
              - Savings
              - Tax Payments
            Payment_Invoice:
              type: string
              description: "To improve processing speed, please include an invoice for any payment request of $3,000 or more"
        description:
          type: string
          description: "Provide an internal purpose / description related to the transaction"
        subject: 
          type: string
          description: "The DRN (Deposit Reference Number) of the user provided to the merchant once the account is registered and activated with fv bank."
        expirationDate:
          type: string
          description: "The date till this payment request is valid. Must be in the format YYYY-MM-DD"
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    accessClient:
      type: apiKey
      name: Access-Client-Token
      in: header
      description: "Access via an access client token, which is obtained when the client is activated. This token is passed in as a header on every request (stateles)."