openapi: 3.0.2
info:
  version: "1.0.0"
  title: "FVNet"
  description: >
    API endpoints exposed for the Merchant Partners.

    # Introduction

    Using these APIs the merchant partners will be able to interact with users to fund their user account or request payments from them. Once the merchant partner is on-boarded at FV bank, they will be issued with an access-client-token and a merchant partner id. All the blow apis are required to be called with the access-client-token in the header.

servers:
- url: 'https://dev.backend.fvbank.us'

paths:
  /run/fvnet/checkAccountStatus/{drn}:
    get:
      tags:
      - "Account"
      summary: "Get the status of the account, ie Active and the balance"
      operationId: checkAccountStatus
      parameters:
      - name: drn
        in: path
        description: "The deposit reference number of the account to check"
        required: true
        schema:
          type: string
      security:
      - accessClient: []
      responses:
        "200":
          description: "Return the balances of the account"
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/accountStatus"
        "500":
          description: "Internal Server Error"
  /run/fvnet/pushfunds:
    post:
      tags:
      - "Transactions"
      summary: "Performs a payment from the given partner to a FVBank user"
      description: "Performs either a direct, scheduled or recurring payment from the owner indicated on the path to the owner specified on the body. The destination user should be informed in the subject parameter. If the subject is system, it will be a payment to a system account. The payment id is returned on the response, and a link to the transaction details is returned on the Location header."
      operationId: "pushFunds"
      requestBody:
        description: "The payment parameters"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/paymentRequest"
      security:
      - accessClient: []
      responses:
        "500":
          description: "Internal server error"

components:
  schemas:
    accountStatus:
      type: object
      properties:
        balance:
          type: string
          example: "100.91"
        status:
          type: string
          example: "ACTIVE"
        availableBalance:
          type: string
          example: "100.91"
        reservedAmount:
          type: string
          example: "0.00"
    paymentRequest:
      type: object
      required:
      - amount
      properties:
        amount:
          type: string
        customValues:
          type: object
          required:
          - Beneficiary_Payment_Purpose
          properties:
            Beneficiary_Payment_Purpose:
              type: string
              enum:
              - Asset Purchase
              - Contract Payment
              - Education Payment
              - Investment Purchase
              - Invoice Payment
              - Loan Payments
              - Materials Purchase
              - Mortgage Payments
              - Payroll
              - Personal/Family Payment
              - Professional Service Payments
              - Rent/Utility Payments
              - Savings
              - Tax Payments
              - Other (describe below)
            Payment_Invoice:
              type: string
              description: "To improve processing speed, please include an invoice for any payment request of $3,000 or more"
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    accessClient:
      type: apiKey
      name: Access-Client-Token
      in: header
      description: "Access via an access client token, which is obtained when the client is activated. This token is passed in as a header on every request (stateles)."