swagger: "2.0"
info:
  description: "It describes the FVNet services for merchant partners"
  version: "1.0.0"
  title: "FVNet"
host: "dev.backend.fvbank.us"
schemes:
- "https"
paths:
  /run/fvnet/checkAccountStatus/{drn}:
    get:
      tags:
      - "fvnet"
      summary: "Get the status of the account, ie Active and the balance"
      operationId: "status"
      produces:
      - "application/json"
      schemes:
      - "https"
      parameters:
      - in: "path"
        name: "drn"
        description: "The deposit reference number of the account to check"
        required: true
        type: string
      security:
        - accessClient: []
      responses:
        "200":
          description: "Return the balances of the account"
        "500":
          description: "Internal server error"
  /run/fvnet/pushfunds:
    post:
      tags:
      - "fvnet"
      summary: "Performs a payment from the given partner to a FVBank user"
      description: "Performs either a direct, scheduled or recurring payment from the owner indicated on the path to the owner specified on the body. The destination user should be informed in the subject parameter. If the subject is system, it will be a payment to a system account. The payment id is returned on the response, and a link to the transaction details is returned on the Location header."
      operationId: "payment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      schemes:
      - "https"
      parameters:
      - in: "body"
        name: "body"
        description: "The payment parameters"
        required: true
        schema:
          $ref: "#/definitions/payment"
      security:
        - accessClient: []
      responses:
        "500":
          description: "Internal server error"
  /run/fvnet/paymentrequest:
    post:
      tags:
      - "fvnet"
      summary: "Performs a payment request from the given partner to a FVBank user"
      operationId: "paymentrequest"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      schemes:
      - "https"
      parameters:
      - in: "body"
        name: "body"
        description: "The payment parameters"
        required: true
        schema:
          $ref: "#/definitions/payment"
      security:
        - accessClient: []
      responses:
        "500":
          description: "Internal server error"
  /api/files/temp:
    post:
      tags:
      - "api"
      summary: "Uploads a new invoice. The returned id can later be used as value of a 'Payment_Invoice' custom field in the fvnet calls"
      operationId: "uploadfile"
      consumes:
         - multipart/form-data
      schemes:
      - "https"
      parameters:
      - name: "file"
        in: "formData"
        description: "The Invoice. Accepted formats: PDF, Word, Images, Excel"
        required: true
        type: file
      - name: "customField"
        in: "formData"
        required: true
        type: string
        description: "Set to 'Payment_Invoice' value always"
      - name: "customFieldKind"
        in: "formData"
        required: true
        type: string
        description: "Set to 'transaction' value always"
      security:
        - accessClient: []
      responses:
        "201":
          description: "Returns an id to be used later in the pushfunds or paymentrequests calls on the 'Payment_Invoice' custom field"
        "500":
          description: "Internal server error"
  /activate-access-client:
    post:
      tags:
        - "activate"
      summary: "Activates a FVNet token"
      description: ""
      consumes:
        - 'text/plain; charset=utf-8'
      parameters:
      - in: "body"
        name: "body"
        description: "The activation code you got during access client creation"
        required: true
        schema:
          $ref: "#/definitions/activate"
      responses:
        200:
          description: OK
      security:
        - basicAuth: []
definitions:
  activate:
    type: "string"
  payment:
    type: "object"
    properties:
      amount:
        type: "string"
      customValues:
        type: "object"
        properties:
          Beneficiary_Payment_Purpose:
            type: "string"
            enum:
            - "Asset Purchase"
            - "Contract Payment"
            - "Education Payment"
            - "Investment Purchase"
            - "Invoice Payment"
            - "Loan Payments"
            - "Materials Purchase"
            - "Mortgage Payments"
            - "Payroll"
            - "Personal/Family Payment"
            - "Professional Service Payments"
            - "Rent/Utility Payments"
            - "Savings"
            - "Tax Payments"
            - "Other (describe below)"
          Payment_Invoice:
            type: "string"
            description: "To improve processing speed, please include an invoice for any payment request of $3,000 or more"
      description:
         type: "string"
      subject:
        type: "string"
        description: "the deposit reference number of the destinatary"
      expirationDate:
        type: "string"
        description: "The date till this payment request is valid. Must be in the format YYYY-MM-DD"
securityDefinitions:
  basicAuth:
    type: basic
  accessClient:
    type: apiKey
    name: Access-Client-Token
    in: header
    description: "Access via an access client token, which is obtained when the client is activated. This token is passed in as a header on every request (stateles)."